import streamlit as st
import time
import pandas as pd
import requests
import hashlib
import re
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from io import BytesIO

# 尝试导入 pptx
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Cm
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN, MSO_AUTO_SIZE
    from pptx.enum.shapes import MSO_SHAPE
except ImportError:
    st.error("Missing dependencies! Please add 'python-pptx' to requirements.txt.")
    st.stop()

# --- 1. 页面基础配置 ---
st.set_page_config(
    page_title="NextGen SEO Auditor",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. 国际化字典 (i18n) ---
TRANSLATIONS = {
    "zh": {
        "sidebar_title": "🔍 AuditAI Pro",
        "sidebar_caption": "深度审计版 v3.1",
        "nav_label": "功能导航",
        "nav_options": ["输入网址", "仪表盘", "数据矩阵", "PPT 生成器"],
        "lang_label": "语言 / Language",
        "clear_data": "清除数据并重置",
        "cache_info": "已缓存 {} 个页面",
        "sitemap_status_title": "Sitemap 状态:",
        
        # PSI 相关
        "psi_settings": "Google PSI API 设置 (可选)",
        "psi_api_key_label": "输入 Google PageSpeed API Key",
        "psi_api_help": "留空则仅进行静态代码检查。填入 Key 可获取首页的真实用户体验数据 (LCP, CLS, INP)。",
        "psi_fetching": "正在调用 Google API 获取真实 CWV 数据...",
        "psi_success": "成功获取真实用户数据！",
        "psi_error": "API 调用失败或无 CrUX 数据",
        
        "input_header": "开始深度审计",
        "input_info": "说明: 新增 Google PageSpeed Insights (PSI) 集成，支持获取真实用户体验数据。",
        "input_label": "输入目标网址",
        "input_placeholder": "https://example.com",
        "max_pages_label": "最大爬取页面数",
        "adv_settings": "高级设置 (Advanced Settings)", 
        "manual_robots": "手动 Robots.txt 地址 (可选)", 
        "manual_sitemaps": "手动 Sitemap 地址 (每行一个, 可选)", 
        "start_btn": "开始深度爬取",
        "error_url": "网址格式错误",
        "spinner_crawl": "正在执行深度审计 (Max {} pages)...", 
        "error_no_data": "未能爬取到任何页面。",
        "success_audit": "审计完成！共分析 {} 个页面。",
        
        "dashboard_header": "执行摘要 (Executive Summary)",
        "warn_no_data": "暂无数据。",
        "kpi_health": "网站健康度",
        "kpi_pages": "已分析页面",
        "kpi_issues": "发现问题总数",
        "kpi_critical": "严重问题",
        "chart_issues": "问题类型分布",
        "chart_no_issues": "未发现明显问题。",
        "chart_status": "HTTP 状态码分布",
        "cwv_title": "核心 Web 指标 (Core Web Vitals) - 真实数据",
        "cwv_source": "数据来源: Google Chrome User Experience Report (CrUX)",
        
        "matrix_header": "爬取数据明细 (Big Sheet)",
        "download_csv": "下载 CSV 报告",
        
        "ppt_header": "演示文稿预览 (Pitch Deck Mode)",
        "ppt_success_no_issues": "无严重问题。",
        "ppt_download_header": "📥 导出报告",
        "ppt_info": "说明：生成的 PPT 已优化为 16:9 宽屏，包含 SERP 预览和深度代码分析。",
        "ppt_btn": "生成并下载美化版 .pptx",
        "ppt_preview_header": "网页版预览",
        "ppt_slide_title": "问题类型:",
        "ppt_severity": "严重程度:",
        "ppt_impact": "影响范围:",
        "ppt_impact_desc": "在已爬取样本中发现 **{}** 个页面。",
        "ppt_desc": "描述:",
        "ppt_sugg": "💡 建议:",
        "ppt_examples": "🔍 示例:",
        "ppt_prev": "⬅️ 上一页",
        "ppt_next": "下一页 ➡️",
        
        "ppt_cover_title": "SEO 深度技术审计报告",
        "ppt_cover_sub": "Generated by AuditAI Pro v3.1",
        "ppt_slide_desc_title": "问题描述 & 影响",
        "ppt_slide_count_title": "样本中受影响页面数: {} 个",
        "ppt_slide_ex_title": "受影响页面示例 & 证据",
        "ppt_slide_sugg_title": "💡 修复建议:",
        "serp_sim_title": "Google 搜索结果模拟:",
    },
    "en": {
        "sidebar_title": "🔍 AuditAI Pro",
        "sidebar_caption": "Deep Audit Edition v3.1",
        "nav_label": "Navigation",
        "nav_options": ["Input URL", "Dashboard", "Data Matrix", "PPT Generator"],
        "lang_label": "Language / 语言",
        "clear_data": "Clear Data & Reset",
        "cache_info": "Cached {} pages",
        "sitemap_status_title": "Sitemap Status:",
        
        # PSI Related
        "psi_settings": "Google PSI API Settings (Optional)",
        "psi_api_key_label": "Enter Google PageSpeed API Key",
        "psi_api_help": "Leave empty for static check only. Enter Key to fetch Real User Metrics (LCP, CLS, INP) for the home page.",
        "psi_fetching": "Fetching real CWV data from Google API...",
        "psi_success": "Real user data fetched!",
        "psi_error": "API Failed or No CrUX Data",
        
        "input_header": "Start Deep Audit",
        "input_info": "Note: Integrated Google PageSpeed Insights (PSI) for real-world user experience data.",
        "input_label": "Target URL",
        "input_placeholder": "https://example.com",
        "max_pages_label": "Max Pages to Crawl",
        "adv_settings": "Advanced Settings", 
        "manual_robots": "Manual Robots.txt URL (Optional)", 
        "manual_sitemaps": "Manual Sitemap URLs (One per line, Optional)", 
        "start_btn": "Start Deep Crawl",
        "error_url": "Invalid URL format",
        "spinner_crawl": "Running Deep Audit (Max {} pages)...", 
        "error_no_data": "No pages crawled.",
        "success_audit": "Audit Complete! Analyzed {} pages.",
        
        "dashboard_header": "Executive Summary",
        "warn_no_data": "No data available.",
        "kpi_health": "Health Score",
        "kpi_pages": "Analyzed Pages",
        "kpi_issues": "Total Issues",
        "kpi_critical": "Critical Issues",
        "chart_issues": "Issue Distribution",
        "chart_no_issues": "No significant issues found.",
        "chart_status": "HTTP Status Codes",
        "cwv_title": "Core Web Vitals - Real User Data",
        "cwv_source": "Source: Google Chrome User Experience Report (CrUX)",
        
        "matrix_header": "Crawled Data Matrix",
        "download_csv": "Download CSV Report",
        
        "ppt_header": "Pitch Deck Preview",
        "ppt_success_no_issues": "No critical issues found.",
        "ppt_download_header": "📥 Export Report",
        "ppt_info": "Note: PPT optimized for 16:9 with SERP simulation and deep code analysis.",
        "ppt_btn": "Generate & Download .pptx",
        "ppt_preview_header": "Web Preview",
        "ppt_slide_title": "Issue Type:",
        "ppt_severity": "Severity:",
        "ppt_impact": "Impact:",
        "ppt_impact_desc": "Affects **{}** pages in crawled sample.",
        "ppt_desc": "Description:",
        "ppt_sugg": "💡 Suggestion:",
        "ppt_examples": "🔍 Examples:",
        "ppt_prev": "⬅️ Previous",
        "ppt_next": "Next ➡️",
        
        "ppt_cover_title": "SEO Technical Audit",
        "ppt_cover_sub": "Generated by AuditAI Pro v3.1",
        "ppt_slide_desc_title": "Description & Impact",
        "ppt_slide_count_title": "Affected Pages (in sample): {}",
        "ppt_slide_ex_title": "Example URLs & Evidence",
        "ppt_slide_sugg_title": "💡 Recommendation:",
        "serp_sim_title": "Google SERP Simulation:",
    }
}

# --- 3. 爬虫核心引擎 (支持多语言) ---

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except:
        return False

def get_content_hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()

def get_browser_headers():
    return {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Connection': 'keep-alive',
    }

# --- Google PSI API Integration ---
def fetch_psi_data(url, api_key):
    """Call Google PageSpeed Insights API"""
    if not api_key: return None
    
    endpoint = f"https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url={url}&key={api_key}&strategy=mobile"
    try:
        response = requests.get(endpoint, timeout=30)
        if response.status_code == 200:
            data = response.json()
            # Extract Crux Data (loadingExperience)
            crux = data.get('loadingExperience', {}).get('metrics', {})
            if not crux: return {"error": "No CrUX data available for this URL."}
            
            return {
                "LCP": crux.get('LARGEST_CONTENTFUL_PAINT_MS', {}).get('percentile', 0) / 1000,
                "CLS": crux.get('CUMULATIVE_LAYOUT_SHIFT_SCORE', {}).get('percentile', 0) / 100,
                "INP": crux.get('INTERACTION_TO_NEXT_PAINT', {}).get('percentile', 0),
                "FCP": crux.get('FIRST_CONTENTFUL_PAINT_MS', {}).get('percentile', 0) / 1000,
            }
        else:
            return {"error": f"API Error: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}

def check_site_level_assets(start_url, lang="zh", manual_robots=None, manual_sitemaps=None):
    issues = []
    sitemap_has_hreflang = False
    
    parsed_url = urlparse(start_url)
    base_url = f"{parsed_url.scheme}://{parsed_url.netloc}"
    headers = get_browser_headers()
    
    # 语言包
    txt = {
        "zh": {
            "no_robots": "缺失 Robots.txt",
            "robots_bad_rule": "Robots.txt 规则风险",
            "robots_no_sitemap": "Robots.txt 未声明 Sitemap",
            "no_sitemap": "Sitemap 访问失败",
            "sitemap_invalid": "Sitemap 格式错误",
            "no_favicon": "站点缺失 Favicon",
        },
        "en": {
            "no_robots": "Missing Robots.txt",
            "robots_bad_rule": "Robots.txt Blocking Risk",
            "robots_no_sitemap": "Sitemap not in Robots.txt",
            "no_sitemap": "Sitemap Access Failed",
            "sitemap_invalid": "Invalid Sitemap Format",
            "no_favicon": "Site Missing Favicon",
        }
    }
    t = txt[lang]

    # --- 1. Robots.txt 逻辑检查 ---
    robots_url = manual_robots if manual_robots else urljoin(base_url, "/robots.txt")
    try:
        r = requests.get(robots_url, headers=headers, timeout=10, allow_redirects=True, stream=True)
        if r.status_code != 200:
            issues.append({"severity": "Medium", "title": t["no_robots"], "desc": f"Status: {r.status_code}", "suggestion": "Ensure robots.txt exists.", "url": robots_url})
        else:
            # 检查 Robots 内容
            content = r.text.lower()
            if "disallow: /" in content and "allow:" not in content:
                 issues.append({"severity": "Critical", "title": t["robots_bad_rule"], "desc": "Found 'Disallow: /' which blocks ALL crawling.", "suggestion": "Remove global disallow rule.", "url": robots_url})
            if "sitemap:" not in content:
                 issues.append({"severity": "Low", "title": t["robots_no_sitemap"], "desc": "Sitemap location not specified in robots.txt.", "suggestion": "Add 'Sitemap: [URL]' directive.", "url": robots_url})
        r.close()
    except: 
        issues.append({"severity": "Medium", "title": t["no_robots"], "desc": "Connection failed.", "suggestion": "Check server config.", "url": robots_url})

    # --- 2. Sitemap 深度检查 ---
    sitemap_urls_to_check = manual_sitemaps if manual_sitemaps else [urljoin(base_url, "/sitemap.xml")]
    any_sitemap_valid = False
    
    for sitemap_url in sitemap_urls_to_check:
        sitemap_url = sitemap_url.strip()
        if not sitemap_url: continue
        try:
            r = requests.get(sitemap_url, headers=headers, timeout=15, allow_redirects=True)
            if r.status_code == 200:
                # 尝试解析 XML
                try:
                    root = ET.fromstring(r.content)
                    any_sitemap_valid = True
                    # 检查 hreflang
                    if 'xhtml' in r.text or 'hreflang' in r.text:
                        sitemap_has_hreflang = True
                except ET.ParseError:
                    if not sitemap_url.endswith('.gz'): # 忽略压缩格式报错
                        issues.append({"severity": "Medium", "title": t["sitemap_invalid"], "desc": "XML parsing failed.", "suggestion": "Check XML syntax.", "url": sitemap_url})
            else:
                if manual_sitemaps:
                    issues.append({"severity": "Low", "title": t["no_sitemap"], "desc": f"Status: {r.status_code}", "suggestion": "Check URL.", "url": sitemap_url})
        except:
            if manual_sitemaps: issues.append({"severity": "Low", "title": t["no_sitemap"], "desc": "Connection failed.", "suggestion": "Check URL.", "url": sitemap_url})

    if not any_sitemap_valid and not manual_sitemaps:
         issues.append({"severity": "Low", "title": t["no_sitemap"], "desc": "Default sitemap not found.", "suggestion": "Ensure sitemap.xml exists.", "url": sitemap_urls_to_check[0]})

    return issues, sitemap_has_hreflang

def analyze_page(url, html_content, status_code, lang="zh", sitemap_has_hreflang=False):
    soup = BeautifulSoup(html_content, 'html.parser')
    issues = []
    
    # 语言包
    txt = {
        "zh": {
            "hreflang_invalid": "Hreflang 代码格式错误",
            "hreflang_invalid_desc": "语言代码不符合 ISO 639-1 标准 (如 'en-US', 'zh-CN')。",
            "hreflang_no_default": "Hreflang 缺失 x-default",
            "hreflang_no_default_desc": "未配置 'x-default' 回退版本，影响非匹配地区用户体验。",
            "alt_bad_quality": "图片 Alt 质量差",
            "alt_bad_quality_desc": "Alt 文本包含无意义词汇（如文件名、'image' 等）或过短。",
            "anchor_bad_quality": "锚文本质量差 (Generic Anchor)",
            "anchor_bad_quality_desc": "使用了通用词汇（如 'Click here'），无法传递链接相关性。",
            "cls_risk": "存在 CLS 布局偏移风险 (CWV)",
            "cls_risk_desc": "检测到 img 标签缺失 width 或 height 属性，会导致页面加载时抖动。",
            # ... (Existing keys)
            "missing_title": "缺失页面标题 (Title)", "short_title": "标题过短", "long_title": "标题过长",
            "missing_desc": "缺失元描述", "short_desc": "元描述过短", "missing_h1": "缺失 H1 标签",
            "missing_viewport": "缺失移动端视口配置", "missing_canonical": "缺失 Canonical 标签",
            "missing_jsonld": "缺失结构化数据", "missing_hreflang": "缺失 Hreflang",
            "soft_404": "疑似软 404 (Soft 404)", "missing_alt": "图片缺失 Alt 属性",
            "duplicate": "发现重复内容"
        },
        "en": {
            "hreflang_invalid": "Invalid Hreflang Code",
            "hreflang_invalid_desc": "Language code format is invalid (Use 'en-US', 'fr-FR').",
            "hreflang_no_default": "Missing x-default Hreflang",
            "hreflang_no_default_desc": "No 'x-default' fallback found for unmatched regions.",
            "alt_bad_quality": "Poor Quality Alt Text",
            "alt_bad_quality_desc": "Alt text uses filenames or generic words like 'image'.",
            "anchor_bad_quality": "Poor Anchor Text (Generic)",
            "anchor_bad_quality_desc": "Generic text (e.g., 'Click here') found. Use descriptive text.",
            "cls_risk": "CLS Layout Shift Risk (CWV)",
            "cls_risk_desc": "Images missing width/height attributes, causing layout jumps.",
            # ...
            "missing_title": "Missing Title Tag", "short_title": "Title Too Short", "long_title": "Title Too Long",
            "missing_desc": "Missing Meta Description", "short_desc": "Meta Description Too Short", "missing_h1": "Missing H1 Tag",
            "missing_viewport": "Missing Mobile Viewport", "missing_canonical": "Missing Canonical Tag",
            "missing_jsonld": "Missing Structured Data", "missing_hreflang": "Missing Hreflang",
            "soft_404": "Suspected Soft 404", "missing_alt": "Images Missing Alt Text",
            "duplicate": "Duplicate Content Detected"
        }
    }
    t = txt[lang]
    
    for script in soup(["script", "style"]): script.extract()
    text_content = soup.get_text().strip()
    content_hash = get_content_hash(text_content)

    # --- 1. Hreflang 深度验证 ---
    hreflangs = soup.find_all('link', hreflang=True)
    if hreflangs:
        has_x_default = False
        invalid_codes = []
        code_pattern = re.compile(r'^[a-z]{2}(-[a-zA-Z]{2})?$|x-default', re.IGNORECASE)
        
        for link in hreflangs:
            code = link.get('hreflang', '').strip()
            if code.lower() == 'x-default': has_x_default = True
            if not code_pattern.match(code): invalid_codes.append(code)
        
        if invalid_codes:
            issues.append({"severity": "High", "title": t["hreflang_invalid"], "desc": f"{t['hreflang_invalid_desc']} Found: {', '.join(invalid_codes[:3])}", "suggestion": "Use ISO 639-1 codes.", "url": url})
        if not has_x_default:
            issues.append({"severity": "Low", "title": t["hreflang_no_default"], "desc": t["hreflang_no_default_desc"], "suggestion": "Add hreflang='x-default'.", "url": url})
    elif not sitemap_has_hreflang:
        issues.append({"severity": "Low", "title": t["missing_hreflang"], "desc": "No hreflang in HTML or Sitemap.", "suggestion": "Add hreflang tags.", "url": url})

    # --- 2. 图片 Alt 质量检查 & CWV (CLS) ---
    images = soup.find_all('img')
    missing_alt = 0
    bad_alt_count = 0
    cls_risk_count = 0
    bad_keywords = ["image", "photo", "picture", "img", "untitled", ".jpg", ".png"]
    
    for img in images:
        alt = img.get('alt', '').strip()
        if not alt: 
            missing_alt += 1
        else:
            if len(alt) < 3 or any(bk in alt.lower() for bk in bad_keywords):
                bad_alt_count += 1
        
        if not img.get('width') or not img.get('height'):
            cls_risk_count += 1

    if missing_alt > 0:
        issues.append({"severity": "Medium", "title": t["missing_alt"], "desc": f"{missing_alt} images missing alt.", "suggestion": "Add descriptive alt text.", "url": url})
    if bad_alt_count > 0:
        issues.append({"severity": "Low", "title": t["alt_bad_quality"], "desc": t["alt_bad_quality_desc"], "suggestion": "Avoid generic keywords.", "url": url, "evidence": f"{bad_alt_count} poor alts"})
    if cls_risk_count > 0:
        issues.append({"severity": "Medium", "title": t["cls_risk"], "desc": t["cls_risk_desc"], "suggestion": "Always specify width/height.", "url": url, "evidence": f"{cls_risk_count} images without dims"})

    # --- 3. 锚文本质量检查 ---
    links = soup.find_all('a', href=True)
    bad_anchors = ["click here", "read more", "learn more", "more", "here", "link", "点击这里", "更多", "详情"]
    found_bad_anchors = []
    
    for link in links:
        anchor_text = link.get_text().strip().lower()
        if anchor_text in bad_anchors:
            found_bad_anchors.append(anchor_text)
