import streamlit as st
import time
import pandas as pd
import requests
import hashlib
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from io import BytesIO

# 尝试导入 pptx
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Cm
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN, MSO_AUTO_SIZE
except ImportError:
    st.error("Missing dependencies! Please add 'python-pptx' to requirements.txt.")
    st.stop()

# --- 1. 页面基础配置 ---
st.set_page_config(
    page_title="NextGen SEO Auditor",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. 国际化字典 (i18n) ---
TRANSLATIONS = {
    "zh": {
        "sidebar_title": "🔍 AuditAI Pro",
        "sidebar_caption": "实时爬虫版 v2.4",
        "nav_label": "功能导航",
        "nav_options": ["输入网址", "仪表盘", "数据矩阵", "PPT 生成器"],
        "lang_label": "语言 / Language",
        "clear_data": "清除数据并重置",
        "cache_info": "已缓存 {} 个页面",
        
        "input_header": "开始新的审计",
        "input_info": "说明: 包含重复内容检测、软404增强检测及美化版 PPT 导出功能。",
        "input_label": "输入目标网址",
        "input_placeholder": "https://example.com",
        "max_pages_label": "最大爬取页面数", # 新增
        "start_btn": "开始真实爬取",
        "error_url": "网址格式错误",
        "spinner_crawl": "正在启动爬虫 (Max {} pages)...", # 修改为动态占位符
        "error_no_data": "未能爬取到任何页面。",
        "success_audit": "审计完成！共分析 {} 个页面。",
        
        "dashboard_header": "执行摘要 (Executive Summary)",
        "warn_no_data": "暂无数据。",
        "kpi_health": "网站健康度",
        "kpi_pages": "已分析页面",
        "kpi_issues": "发现问题总数",
        "kpi_critical": "严重问题",
        "chart_issues": "问题类型分布",
        "chart_no_issues": "未发现明显问题。",
        "chart_status": "HTTP 状态码分布",
        
        "matrix_header": "全站数据明细 (Big Sheet)",
        "download_csv": "下载 CSV 报告",
        
        "ppt_header": "演示文稿预览 (Pitch Deck Mode)",
        "ppt_success_no_issues": "无严重问题。",
        "ppt_download_header": "📥 导出报告",
        "ppt_info": "说明：生成的 PPT 已优化为 16:9 宽屏，采用现代排版和配色。",
        "ppt_btn": "生成并下载美化版 .pptx",
        "ppt_preview_header": "网页版预览",
        "ppt_slide_title": "问题类型:",
        "ppt_severity": "严重程度:",
        "ppt_impact": "影响范围:",
        "ppt_impact_desc": "全站共 **{}** 个页面。",
        "ppt_desc": "描述:",
        "ppt_sugg": "💡 建议:",
        "ppt_examples": "🔍 示例:",
        "ppt_prev": "⬅️ 上一页",
        "ppt_next": "下一页 ➡️",
        
        # PPT Static Text
        "ppt_cover_title": "SEO 技术审计报告",
        "ppt_cover_sub": "Generated by AuditAI Pro",
        "ppt_slide_desc_title": "问题描述 & 影响",
        "ppt_slide_count_title": "受影响页面数量: {} 个",
        "ppt_slide_ex_title": "受影响页面示例",
        "ppt_slide_sugg_title": "💡 修复建议:",
    },
    "en": {
        "sidebar_title": "🔍 AuditAI Pro",
        "sidebar_caption": "Live Crawler Edition v2.4",
        "nav_label": "Navigation",
        "nav_options": ["Input URL", "Dashboard", "Data Matrix", "PPT Generator"],
        "lang_label": "Language / 语言",
        "clear_data": "Clear Data & Reset",
        "cache_info": "Cached {} pages",
        
        "input_header": "Start New Audit",
        "input_info": "Note: Includes Duplicate Content detection, Soft 404s, and Styled PPT Export.",
        "input_label": "Target URL",
        "input_placeholder": "https://example.com",
        "max_pages_label": "Max Pages to Crawl", # New
        "start_btn": "Start Live Crawl",
        "error_url": "Invalid URL format",
        "spinner_crawl": "Starting Crawler (Max {} pages)...", # Dynamic
        "error_no_data": "No pages crawled.",
        "success_audit": "Audit Complete! Analyzed {} pages.",
        
        "dashboard_header": "Executive Summary",
        "warn_no_data": "No data available.",
        "kpi_health": "Health Score",
        "kpi_pages": "Analyzed Pages",
        "kpi_issues": "Total Issues",
        "kpi_critical": "Critical Issues",
        "chart_issues": "Issue Distribution",
        "chart_no_issues": "No significant issues found.",
        "chart_status": "HTTP Status Codes",
        
        "matrix_header": "Data Matrix (Big Sheet)",
        "download_csv": "Download CSV Report",
        
        "ppt_header": "Pitch Deck Preview",
        "ppt_success_no_issues": "No critical issues found.",
        "ppt_download_header": "📥 Export Report",
        "ppt_info": "Note: PPT is optimized for 16:9 widescreen with modern layout.",
        "ppt_btn": "Generate & Download .pptx",
        "ppt_preview_header": "Web Preview",
        "ppt_slide_title": "Issue Type:",
        "ppt_severity": "Severity:",
        "ppt_impact": "Impact:",
        "ppt_impact_desc": "Affects **{}** pages site-wide.",
        "ppt_desc": "Description:",
        "ppt_sugg": "💡 Suggestion:",
        "ppt_examples": "🔍 Examples:",
        "ppt_prev": "⬅️ Previous",
        "ppt_next": "Next ➡️",
        
        # PPT Static Text
        "ppt_cover_title": "SEO Technical Audit",
        "ppt_cover_sub": "Generated by AuditAI Pro",
        "ppt_slide_desc_title": "Description & Impact",
        "ppt_slide_count_title": "Affected Pages: {}",
        "ppt_slide_ex_title": "Example URLs",
        "ppt_slide_sugg_title": "💡 Recommendation:",
    }
}

# --- 3. 爬虫核心引擎 (支持多语言) ---

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except:
        return False

def get_content_hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()

def check_site_level_assets(start_url, lang="zh"):
    """检查站点级别的 SEO 资产"""
    issues = []
    parsed_url = urlparse(start_url)
    base_url = f"{parsed_url.scheme}://{parsed_url.netloc}"
    
    # 文本字典
    txt = {
        "zh": {
            "no_robots": "缺失 Robots.txt",
            "no_robots_desc": "无法在根目录找到 robots.txt 文件。",
            "no_robots_sugg": "在网站根目录创建 robots.txt 文件。",
            "no_sitemap": "根目录未发现 Sitemap.xml",
            "no_sitemap_desc": "根目录无 sitemap.xml。",
            "no_sitemap_sugg": "确保 Sitemap 可访问并在 robots.txt 中引用。"
        },
        "en": {
            "no_robots": "Missing Robots.txt",
            "no_robots_desc": "Robots.txt file not found in root directory.",
            "no_robots_sugg": "Create robots.txt in root directory.",
            "no_sitemap": "Sitemap.xml Not Found",
            "no_sitemap_desc": "Sitemap.xml not found in root directory.",
            "no_sitemap_sugg": "Ensure Sitemap is accessible and linked in robots.txt."
        }
    }
    t = txt[lang]

    # 1. Robots.txt
    robots_url = urljoin(base_url, "/robots.txt")
    try:
        r = requests.head(robots_url, timeout=5)
        if r.status_code != 200:
            issues.append({
                "severity": "Medium",
                "title": t["no_robots"],
                "desc": t["no_robots_desc"],
                "suggestion": t["no_robots_sugg"],
                "url": robots_url,
                "meta": f"Status: {r.status_code}"
            })
    except:
        pass 

    # 2. Sitemap.xml
    sitemap_url = urljoin(base_url, "/sitemap.xml")
    try:
        r = requests.head(sitemap_url, timeout=5)
        if r.status_code != 200:
            issues.append({
                "severity": "Low",
                "title": t["no_sitemap"],
                "desc": t["no_sitemap_desc"],
                "suggestion": t["no_sitemap_sugg"],
                "url": sitemap_url,
                "meta": f"Status: {r.status_code}"
            })
    except:
        pass

    return issues

def analyze_page(url, html_content, status_code, lang="zh"):
    """分析单个页面，支持多语言返回"""
    soup = BeautifulSoup(html_content, 'html.parser')
    issues = []
    
    # 语言包
    txt = {
        "zh": {
            "missing_title": "缺失页面标题 (Title)",
            "missing_title_desc": "页面没有 <title> 标签。",
            "missing_title_sugg": "添加描述性标题。",
            "short_title": "标题过短",
            "short_title_desc": "标题过短，难以覆盖关键词。",
            "short_title_sugg": "扩充标题长度。",
            "long_title": "标题过长",
            "long_title_desc": "标题过长，可能被截断。",
            "long_title_sugg": "精简标题长度。",
            "missing_desc": "缺失元描述",
            "missing_desc_desc": "缺失 Meta Description，影响点击率。",
            "missing_desc_sugg": "添加 Meta Description。",
            "short_desc": "元描述过短",
            "short_desc_desc": "元描述内容过少。",
            "short_desc_sugg": "扩充元描述至 120-160 字符。",
            "missing_h1": "缺失 H1 标签",
            "missing_h1_desc": "页面缺乏 H1 主标题。",
            "missing_h1_sugg": "添加唯一的 H1 标签。",
            "missing_viewport": "缺失移动端视口配置",
            "missing_viewport_desc": "未配置 Viewport，移动端体验差。",
            "missing_viewport_sugg": "添加 viewport meta 标签。",
            "missing_canonical": "缺失 Canonical 标签",
            "missing_canonical_desc": "未指定规范链接，可能导致重复内容。",
            "missing_canonical_sugg": "添加 canonical 标签指向标准 URL。",
            "missing_favicon": "缺失 Favicon",
            "missing_favicon_desc": "未设置网站图标。",
            "missing_favicon_sugg": "添加 link rel='icon'。",
            "missing_jsonld": "缺失结构化数据",
            "missing_jsonld_desc": "未检测到 JSON-LD。",
            "missing_jsonld_sugg": "添加 JSON-LD 结构化数据。",
            "missing_hreflang": "缺失 Hreflang",
            "missing_hreflang_desc": "未发现语言区域标记。",
            "missing_hreflang_sugg": "如为多语言站点请添加 hreflang。",
            "url_underscore": "URL 包含下划线",
            "url_underscore_desc": "建议使用连字符 (-)。",
            "url_underscore_sugg": "替换下划线为连字符。",
            "url_uppercase": "URL 包含大写字母",
            "url_uppercase_desc": "建议统一使用小写。",
            "url_uppercase_sugg": "转换为小写 URL。",
            "js_links": "发现 JS 伪链接",
            "js_links_desc": "使用了 href='javascript:'，爬虫无法抓取。",
            "js_links_sugg": "使用标准 <a href>。",
            "soft_404": "疑似软 404 (Soft 404)",
            "soft_404_desc": "返回 200 但内容显示未找到。",
            "soft_404_sugg": "配置服务器返回 404 状态码。",
            "missing_alt": "图片缺失 Alt 属性",
            "missing_alt_desc": "图片缺少替代文本。",
            "missing_alt_sugg": "添加 alt 属性。",
            "duplicate": "发现重复内容",
            "duplicate_desc": "内容与另一页面高度重复。",
            "duplicate_sugg": "使用 Canonical 或合并页面。"
        },
        "en": {
            "missing_title": "Missing Title Tag",
            "missing_title_desc": "Page has no <title> tag.",
            "missing_title_sugg": "Add a descriptive title.",
            "short_title": "Title Too Short",
            "short_title_desc": "Title is too short for keywords.",
            "short_title_sugg": "Increase title length.",
            "long_title": "Title Too Long",
            "long_title_desc": "Title may be truncated in SERPs.",
            "long_title_sugg": "Shorten the title.",
            "missing_desc": "Missing Meta Description",
            "missing_desc_desc": "Missing description affects CTR.",
            "missing_desc_sugg": "Add a meta description.",
            "short_desc": "Meta Description Too Short",
            "short_desc_desc": "Description content is too thin.",
            "short_desc_sugg": "Expand to 120-160 chars.",
            "missing_h1": "Missing H1 Tag",
            "missing_h1_desc": "Page lacks a main H1 heading.",
            "missing_h1_sugg": "Add a unique H1 tag.",
            "missing_viewport": "Missing Mobile Viewport",
            "missing_viewport_desc": "No viewport tag found.",
            "missing_viewport_sugg": "Add viewport meta tag.",
            "missing_canonical": "Missing Canonical Tag",
            "missing_canonical_desc": "Canonical URL not specified.",
            "missing_canonical_sugg": "Add canonical link tag.",
            "missing_favicon": "Missing Favicon",
            "missing_favicon_desc": "No site icon detected.",
            "missing_favicon_sugg": "Add link rel='icon'.",
            "missing_jsonld": "Missing Structured Data",
            "missing_jsonld_desc": "No JSON-LD detected.",
            "missing_jsonld_sugg": "Add JSON-LD schema.",
            "missing_hreflang": "Missing Hreflang",
            "missing_hreflang_desc": "No language/region targeting found.",
            "missing_hreflang_sugg": "Add hreflang if multilingual.",
            "url_underscore": "URL Contains Underscores",
            "url_underscore_desc": "Hyphens (-) are preferred.",
            "url_underscore_sugg": "Replace underscores with hyphens.",
            "url_uppercase": "URL Contains Uppercase",
            "url_uppercase_desc": "URLs are case-sensitive.",
            "url_uppercase_sugg": "Use lowercase URLs.",
            "js_links": "JavaScript Pseudo-links",
            "js_links_desc": "href='javascript:' found.",
            "js_links_sugg": "Use standard <a href>.",
            "soft_404": "Suspected Soft 404",
            "soft_404_desc": "Returns 200 but content says 'Not Found'.",
            "soft_404_sugg": "Return 404 HTTP status code.",
            "missing_alt": "Images Missing Alt Text",
            "missing_alt_desc": "Images lack alternative text.",
            "missing_alt_sugg": "Add alt attributes.",
            "duplicate": "Duplicate Content Detected",
            "duplicate_desc": "Content matches another page.",
            "duplicate_sugg": "Use canonicals or merge pages."
        }
    }
    t = txt[lang]
    
    # 提取纯文本
    for script in soup(["script", "style"]):
        script.extract()
    text_content = soup.get_text().strip()
    text_content_lower = text_content.lower()
    content_hash = get_content_hash(text_content)

    # --- 检查逻辑 (使用 t[key] 获取文本) ---
    
    # 1. Title
    title_tag = soup.title
    title = title_tag.string.strip() if title_tag and title_tag.string else None
    
    if not title:
        issues.append({"severity": "High", "title": t["missing_title"], "desc": t["missing_title_desc"], "suggestion": t["missing_title_sugg"], "url": url})
    elif len(title) < 10:
         issues.append({"severity": "Medium", "title": t["short_title"], "desc": t["short_title_desc"], "suggestion": t["short_title_sugg"], "url": url})
    elif len(title) > 60:
         issues.append({"severity": "Low", "title": t["long_title"], "desc": t["long_title_desc"], "suggestion": t["long_title_sugg"], "url": url})

    # 2. Meta Description
    meta_desc = soup.find('meta', attrs={'name': 'description'})
    desc_content = meta_desc['content'].strip() if meta_desc and meta_desc.get('content') else None
    
    if not desc_content:
        issues.append({"severity": "High", "title": t["missing_desc"], "desc": t["missing_desc_desc"], "suggestion": t["missing_desc_sugg"], "url": url})
    elif len(desc_content) < 50:
        issues.append({"severity": "Low", "title": t["short_desc"], "desc": t["short_desc_desc"], "suggestion": t["short_desc_sugg"], "url": url})

    # 3. H1
    h1 = soup.find('h1')
    h1_text = h1.get_text().strip() if h1 else "No H1"
    if not h1:
        issues.append({"severity": "High", "title": t["missing_h1"], "desc": t["missing_h1_desc"], "suggestion": t["missing_h1_sugg"], "url": url})

    # 4. Viewport
    viewport = soup.find('meta', attrs={'name': 'viewport'})
    if not viewport:
        issues.append({"severity": "Critical", "title": t["missing_viewport"], "desc": t["missing_viewport_desc"], "suggestion": t["missing_viewport_sugg"], "url": url})

    # 5. Canonical
    canonical = soup.find('link', attrs={'rel': 'canonical'})
    if not canonical:
        issues.append({"severity": "Medium", "title": t["missing_canonical"], "desc": t["missing_canonical_desc"], "suggestion": t["missing_canonical_sugg"], "url": url})

    # 6. Favicon
    favicon = soup.find('link', rel=lambda x: x and 'icon' in x.lower())
    if not favicon:
         issues.append({"severity": "Low", "title": t["missing_favicon"], "desc": t["missing_favicon_desc"], "suggestion": t["missing_favicon_sugg"], "url": url})

    # 7. JSON-LD
    schema = soup.find('script', type='application/ld+json')
    if not schema:
         issues.append({"severity": "Medium", "title": t["missing_jsonld"], "desc": t["missing_jsonld_desc"], "suggestion": t["missing_jsonld_sugg"], "url": url})

    # 8. Hreflang
    hreflang = soup.find('link', hreflang=True)
    if not hreflang:
        issues.append({"severity": "Low", "title": t["missing_hreflang"], "desc": t["missing_hreflang_desc"], "suggestion": t["missing_hreflang_sugg"], "url": url})

    # 9. URL Structure
    parsed_url = urlparse(url)
    path = parsed_url.path
    if '_' in path:
         issues.append({"severity": "Low", "title": t["url_underscore"], "desc": t["url_underscore_desc"], "suggestion": t["url_underscore_sugg"], "url": url})
    if any(c.isupper() for c in path):
         issues.append({"severity": "Medium", "title": t["url_uppercase"], "desc": t["url_uppercase_desc"], "suggestion": t["url_uppercase_sugg"], "url": url})

    # 10. JS Links
    js_links = soup.find_all('a', href=lambda x: x and x.lower().startswith('javascript:'))
    if js_links:
        issues.append({"severity": "High", "title": t["js_links"], "desc": t["js_links_desc"], "suggestion": t["js_links_sugg"], "url": url, "meta": f"Count: {len(js_links)}"})

    # 11. Soft 404
    is_soft_404 = False
    error_keywords = ["page not found", "404 error", "页面未找到", "404 错误"]
    if title and any(k in title.lower() for k in error_keywords): is_soft_404 = True
    elif h1_text != "No H1" and any(k in h1_text.lower() for k in error_keywords): is_soft_404 = True
    elif any(k in text_content_lower[:500] for k in error_keywords): is_soft_404 = True

    if status_code == 200 and is_soft_404:
        issues.append({"severity": "Critical", "title": t["soft_404"], "desc": t["soft_404_desc"], "suggestion": t["soft_404_sugg"], "url": url})
        
    # 12. Alt
    images = soup.find_all('img')
    missing_alt = 0
    for img in images:
        if not img.get('alt'): missing_alt += 1
    if missing_alt > 0:
        issues.append({"severity": "Medium", "title": t["missing_alt"], "desc": t["missing_alt_desc"], "suggestion": t["missing_alt_sugg"], "url": url, "meta": f"{missing_alt} images"})

    # Internal Links
    internal_links = set()
    base_domain = urlparse(url).netloc
    for a in soup.find_all('a', href=True):
        link = urljoin(url, a['href'])
        parsed_link = urlparse(link)
        if parsed_link.netloc == base_domain:
            if not any(link.lower().endswith(ext) for ext in ['.png', '.jpg', '.jpeg', '.gif', '.pdf', '.css', '.js', '.zip']):
                internal_links.add(link)

    return {
        "URL": url,
        "Status": status_code,
        "Title": title or "No Title",
        "H1": h1_text,
        "Links_Count": len(internal_links),
        "Issues_Count": len(issues),
        "Content_Hash": content_hash
    }, issues, internal_links

def crawl_website(start_url, max_pages=100, lang="zh"):
    """执行爬取，传递语言参数"""
    visited = set()
    seen_hashes = {}
    queue = [start_url]
    results_data = []
    all_issues = []
    
    # 获取对应语言的 UI 文本
    t_dup_title = "Duplicate Content Detected" if lang == "en" else "发现重复内容"
    t_dup_desc = "Content matches another page." if lang == "en" else "内容与另一页面高度重复。"
    t_dup_sugg = "Use canonicals or merge pages." if lang == "en" else "使用 Canonical 或合并页面。"
    
    progress_bar = st.progress(0, text="Initializing...")
    
    try:
        site_issues = check_site_level_assets(start_url, lang=lang)
        all_issues.extend(site_issues)
    except Exception as e:
        st.toast(f"Site-check failed: {str(e)}")

    pages_crawled = 0
    
    while queue and pages_crawled < max_pages:
        url = queue.pop(0)
        if url in visited: continue
        visited.add(url)
        pages_crawled += 1
        
        progress = int((pages_crawled / max_pages) * 100)
        progress_bar.progress(progress, text=f"Crawling ({pages_crawled}/{max_pages}): {url}")
        
        try:
            headers = {'User-Agent': 'Mozilla/5.0 (compatible; SEOAuditBot/2.0)'}
            response = requests.get(url, headers=headers, timeout=10)
            
            content_type = response.headers.get('Content-Type', '').lower()
            if 'text/html' in content_type:
                # 传递 lang 参数
                page_data, page_issues, new_links = analyze_page(url, response.content, response.status_code, lang=lang)
                
                # Duplicate Check
                current_hash = page_data['Content_Hash']
                if current_hash in seen_hashes:
                    original_url = seen_hashes[current_hash]
                    page_issues.append({
                        "severity": "High", "title": t_dup_title, "desc": f"{t_dup_desc} ({original_url})", 
                        "suggestion": t_dup_sugg, "url": url, "meta": f"Duplicate of: {original_url}"
                    })
                else:
                    seen_hashes[current_hash] = url

                results_data.append(page_data)
                all_issues.extend(page_issues)
                
                for link in new_links:
                    if link not in visited and link not in queue: queue.append(link)
        except Exception as e:
            pass
    
    progress_bar.progress(100, text="Done!")
    time.sleep(0.5)
    progress_bar.empty()
    return results_data, all_issues

def create_styled_pptx(slides_data, lang="zh"):
    """生成 PPT，支持多语言静态文本"""
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    txt = TRANSLATIONS[lang] # 使用全局翻译字典
    
    # 修复：直接操作 font_obj，不再访问 .font 属性
    def set_font(font_obj, size, bold=False, color=None):
        font_obj.size = Pt(size)
        font_obj.name = 'Microsoft YaHei' if lang == "zh" else 'Arial'
        font_obj.bold = bold
        if color: font_obj.color.rgb = color

    # --- Cover ---
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg_shape = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.333), Inches(7.5))
    bg_shape.fill.solid()
    bg_shape.fill.fore_color.rgb = RGBColor(18, 52, 86)
    bg_shape.line.fill.background()

    title_box = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(2))
    p = title_box.text_frame.add_paragraph()
    p.text = txt["ppt_cover_title"]
    p.alignment = PP_ALIGN.CENTER
    set_font(p.font, 54, True, RGBColor(255, 255, 255))
    
    sub_box = slide.shapes.add_textbox(Inches(1), Inches(4), Inches(11), Inches(1))
    p_sub = sub_box.text_frame.add_paragraph()
    p_sub.text = txt["ppt_cover_sub"]
    p_sub.alignment = PP_ALIGN.CENTER
    set_font(p_sub.font, 24, False, RGBColor(200, 200, 200))

    # --- Slides ---
    for issue in slides_data:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        
        # Header
        header_shape = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.333), Inches(1.2))
        header_shape.fill.solid()
        header_shape.fill.fore_color.rgb = RGBColor(240, 242, 246)
        header_shape.line.fill.background()
        
        header_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(10), Inches(0.8))
        p = header_box.text_frame.add_paragraph()
        p.text = issue['title']
        set_font(p.font, 32, True, RGBColor(50, 50, 50))
        
        # Severity
        sev_color = RGBColor(220, 53, 69) if issue['severity'] == "Critical" else RGBColor(253, 126, 20)
        sev_box = slide.shapes.add_textbox(Inches(11), Inches(0.35), Inches(2), Inches(0.5))
        p = sev_box.text_frame.add_paragraph()
        p.text = f"{issue['severity']}"
        p.alignment = PP_ALIGN.CENTER
        set_font(p.font, 18, True, sev_color)
        
        # Left: Desc
        desc_title_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(6), Inches(0.5))
        p = desc_title_box.text_frame.add_paragraph()
        p.text = txt["ppt_slide_desc_title"]
        set_font(p.font, 18, True, RGBColor(30, 30, 30))
        
        desc_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.0), Inches(6), Inches(2.5))
        tf = desc_box.text_frame
        tf.word_wrap = True
        tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE # Add this
        p = tf.add_paragraph()
        p.text = issue['desc']
        set_font(p.font, 14, False, RGBColor(80, 80, 80))
        
        count_box = slide.shapes.add_textbox(Inches(0.5), Inches(3.5), Inches(6), Inches(0.5))
        p = count_box.text_frame.add_paragraph()
        p.text = txt["ppt_slide_count_title"].format(issue['count'])
        set_font(p.font, 14, True, RGBColor(100, 100, 100))

        # Right: Examples
        ex_title_box = slide.shapes.add_textbox(Inches(7), Inches(1.5), Inches(5.8), Inches(0.5))
        p = ex_title_box.text_frame.add_paragraph()
        p.text = txt["ppt_slide_ex_title"]
        set_font(p.font, 18, True, RGBColor(30, 30, 30))
        
        ex_box = slide.shapes.add_textbox(Inches(7), Inches(2.0), Inches(5.8), Inches(2.5))
        tf = ex_box.text_frame
        tf.word_wrap = True
        tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE # Add this
        for ex_url in issue['examples'][:5]:
            p = tf.add_paragraph()
            p.text = f"• {ex_url}"
            set_font(p.font, 12, False, RGBColor(0, 102, 204))
            p.space_after = Pt(6)

        # Bottom: Suggestion
        sugg_bg = slide.shapes.add_shape(1, Inches(0.5), Inches(5.5), Inches(12.333), Inches(1.5))
        sugg_bg.fill.solid()
        sugg_bg.fill.fore_color.rgb = RGBColor(230, 244, 234)
        sugg_bg.line.color.rgb = RGBColor(40, 167, 69)
        
        sugg_box = slide.shapes.add_textbox(Inches(0.7), Inches(5.6), Inches(11.9), Inches(1.3))
        tf = sugg_box.text_frame
        tf.word_wrap = True
        tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE # Add this
        
        p = tf.add_paragraph()
        p.text = txt["ppt_slide_sugg_title"]
        set_font(p.font, 16, True, RGBColor(21, 87, 36))
        
        p = tf.add_paragraph()
        p.text = issue['suggestion']
        set_font(p.font, 14, False, RGBColor(21, 87, 36))
        p.space_before = Pt(5)

    binary_output = BytesIO()
    prs.save(binary_output)
    binary_output.seek(0)
    return binary_output

# --- 4. Init Session ---
if 'audit_data' not in st.session_state: st.session_state['audit_data'] = None
if 'audit_issues' not in st.session_state: st.session_state['audit_issues'] = []
if 'language' not in st.session_state: st.session_state['language'] = "zh" # 默认语言

# --- 5. Sidebar ---
# 获取当前语言对应的 UI 文本
lang = st.session_state['language']
ui = TRANSLATIONS[lang]

with st.sidebar:
    st.title(ui["sidebar_title"])
    st.caption(ui["sidebar_caption"])
    
    # 语言切换
    st.divider()
    selected_lang = st.radio(ui["lang_label"], ["中文", "English"], index=0 if lang=="zh" else 1)
    new_lang = "zh" if selected_lang == "中文" else "en"
    
    if new_lang != lang:
        st.session_state['language'] = new_lang
        st.rerun()
    
    st.divider()
    
    menu_options = ui["nav_options"]
    # 映射选择回内部 key
    menu_map = {ui["nav_options"][i]: ["input", "dashboard", "matrix", "ppt"][i] for i in range(4)}
    
    selected_menu = st.radio(ui["nav_label"], menu_options)
    menu_key = menu_map[selected_menu]
    
    st.divider()
    if st.session_state['audit_data'] is not None:
        st.success(ui["cache_info"].format(len(st.session_state['audit_data'])))
        if st.button(ui["clear_data"]):
            st.session_state['audit_data'] = None
            st.session_state['audit_issues'] = []
            st.rerun()

# --- 6. Main Logic ---

if menu_key == "input":
    st.header(ui["input_header"])
    st.info(ui["input_info"])
    
    col1, col2 = st.columns([3, 1])
    with col1:
        url_input = st.text_input(ui["input_label"], placeholder=ui["input_placeholder"])
    with col2:
        max_pages = st.number_input(ui.get("max_pages_label", "Max Pages / 最大页面数"), min_value=1, max_value=1000, value=100)
    
    start_btn = st.button(ui["start_btn"], type="primary", use_container_width=True)
    
    if start_btn and url_input:
        if not is_valid_url(url_input):
            st.error(ui["error_url"])
        else:
            with st.spinner(ui["spinner_crawl"].format(max_pages)):
                # 传递当前语言 lang 和 max_pages
                data, issues = crawl_website(url_input, max_pages=max_pages, lang=lang)
                if not data:
                    st.error(ui["error_no_data"])
                else:
                    st.session_state['audit_data'] = data
                    st.session_state['audit_issues'] = issues
                    st.success(ui["success_audit"].format(len(data)))
                    st.balloons()

elif menu_key == "dashboard":
    st.header(ui["dashboard_header"])
    if st.session_state['audit_data'] is None:
        st.warning(ui["warn_no_data"])
    else:
        df = pd.DataFrame(st.session_state['audit_data'])
        issues = st.session_state['audit_issues']
        
        total = len(issues)
        score = max(0, 100 - int(total * 0.5))
        critical = len([i for i in issues if i['severity'] == 'Critical'])
        
        k1, k2, k3, k4 = st.columns(4)
        k1.metric(ui["kpi_health"], f"{score}/100")
        k2.metric(ui["kpi_pages"], str(len(df)))
        k3.metric(ui["kpi_issues"], str(total), delta_color="inverse")
        k4.metric(ui["kpi_critical"], str(critical), delta_color="inverse")
        
        st.divider()
        c1, c2 = st.columns(2)
        with c1:
            st.subheader(ui["chart_issues"])
            if issues:
                st.bar_chart(pd.DataFrame(issues)['title'].value_counts())
            else:
                st.info(ui["chart_no_issues"])
        with c2:
            st.subheader(ui["chart_status"])
            if not df.empty:
                st.bar_chart(df['Status'].value_counts())

elif menu_key == "matrix":
    st.header(ui["matrix_header"])
    if st.session_state['audit_data'] is None:
        st.warning(ui["warn_no_data"])
    else:
        df = pd.DataFrame(st.session_state['audit_data'])
        st.dataframe(
            df,
            column_config={
                "URL": st.column_config.LinkColumn("URL"),
                "Status": st.column_config.NumberColumn("Status", format="%d"),
            },
            use_container_width=True,
            hide_index=True
        )
        csv = df.to_csv(index=False).encode('utf-8')
        st.download_button(ui["download_csv"], csv, "audit_report.csv", "text/csv")

elif menu_key == "ppt":
    st.header(ui["ppt_header"])
    if st.session_state['audit_data'] is None:
        st.warning(ui["warn_no_data"])
    elif not st.session_state['audit_issues']:
        st.success(ui["ppt_success_no_issues"])
    else:
        # Group issues
        raw_issues = st.session_state['audit_issues']
        grouped = {}
        for i in raw_issues:
            t = i['title']
            if t not in grouped:
                grouped[t] = {
                    "title": t, "severity": i['severity'], "desc": i['desc'], 
                    "suggestion": i['suggestion'], "count": 0, "examples": []
                }
            grouped[t]['count'] += 1
            if len(grouped[t]['examples']) < 5: grouped[t]['examples'].append(i['url'])
        
        sov_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
        slides = sorted(list(grouped.values()), key=lambda x: (sov_order.get(x['severity'], 3), -x['count']))

        # Download
        st.write(f"### {ui['ppt_download_header']}")
        st.info(ui["ppt_info"])
        if st.button(ui["ppt_btn"]):
            with st.spinner("Generating..."):
                # 传递当前语言 lang
                pptx = create_styled_pptx(slides, lang=lang)
                fname = f"seo_audit_report_{lang}.pptx"
                st.download_button(ui["ppt_btn"], pptx, fname, "application/vnd.openxmlformats-officedocument.presentationml.presentation")

        st.divider()
        st.subheader(ui["ppt_preview_header"])
        
        if 'slide_index' not in st.session_state: st.session_state.slide_index = 0
        if st.session_state.slide_index >= len(slides): st.session_state.slide_index = 0
        
        s = slides[st.session_state.slide_index]
        
        with st.container(border=True):
            st.markdown(f"### {ui['ppt_slide_title']} {s['title']}")
            c1, c2 = st.columns([1, 1])
            with c1:
                color = "red" if s['severity'] == "Critical" else "orange" if s['severity'] == "High" else "blue"
                st.markdown(f"**{ui['ppt_severity']}** :{color}[{s['severity']}]")
                st.markdown(f"**{ui['ppt_impact']}** {ui['ppt_impact_desc'].format(s['count'])}")
                st.markdown(f"**{ui['ppt_desc']}** {s['desc']}")
                st.info(f"{ui['ppt_sugg']} {s['suggestion']}")
            with c2:
                st.markdown(f"**{ui['ppt_examples']}**")
                for ex in s['examples']: st.markdown(f"- `{ex}`")

        cp, ct, cn = st.columns([1, 2, 1])
        with cp:
            if st.button(ui["ppt_prev"]):
                st.session_state.slide_index = max(0, st.session_state.slide_index - 1)
                st.rerun()
        with ct:
            st.markdown(f"<div style='text-align: center'>Slide {st.session_state.slide_index + 1} / {len(slides)}</div>", unsafe_allow_html=True)
        with cn:
            if st.button(ui["ppt_next"]):
                st.session_state.slide_index = min(len(slides) - 1, st.session_state.slide_index + 1)
                st.rerun()
